version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${PORT}:5432"
    volumes:
      - stock-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USERNAME} -d ${DB_NAME}"]
      interval: 6s
      timeout: 4s
      retries: 5
    
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  stock-data:
